"""Render MossDL's promotional graphics and demo video from the HTML kit.

    python docs/brand/render.py            # icons, stills and the demo
    python docs/brand/render.py icons      # regenerate kit/icons.js from src/figma/icons.tsx
    python docs/brand/render.py stills     # PNGs only (add names to limit: stills hero-dark)
    python docs/brand/render.py demo       # demo.mp4, demo-light.mp4, demo(-dark|-light).gif, demo-poster.png
    python docs/brand/render.py demo dark  # one theme only

Pages are opened from disk in a headless Chromium (Clearcote when installed,
otherwise patchright's own). Stills are captured at device scale 2 and
downsampled to their listed size. The demo is seeked frame by frame through
window.__seek(t) and encoded with ffmpeg, so every frame is deterministic.
"""
from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
FFMPEG = shutil.which("ffmpeg") or r"C:\ffmpeg\bin\ffmpeg.exe"

# name, page (relative to docs/brand), CSS width, CSS height
STILLS = [
    ("social-preview", "scenes/social.html", 1280, 640),
    ("hero-dark", "scenes/hero.html?theme=dark", 1600, 800),
    ("hero-light", "scenes/hero.html?theme=light", 1600, 800),
    ("feature-downloads", "scenes/feature.html?f=downloads", 1200, 700),
    ("feature-explore", "scenes/feature.html?f=explore", 1200, 700),
    ("feature-following", "scenes/feature.html?f=following", 1200, 700),
    ("feature-connections", "scenes/feature.html?f=connections", 1200, 700),
    ("feature-captchas", "scenes/feature.html?f=captchas", 1200, 700),
]
DEMO = {"page": "demo/demo.html?capture=1", "w": 1600, "h": 900, "scale": 1.2, "fps": 30}
GIF = {"width": 880, "fps": 10, "start": 2.0, "colors": 128}
POSTER_AT = 15.5


def gen_icons() -> None:
    """Copy the app's icon paths (src/figma/icons.tsx `ic`) into kit/icons.js."""
    src = (ROOT / "src/figma/icons.tsx").read_text(encoding="utf-8")
    block = src[src.index("export const ic = {"):]
    block = block[: block.index("\n};")]
    icons = dict(re.findall(r'^\s{2}(\w+):\s*"([^"]+)"', re.sub(r":\s*\n\s+\"", ': "', block), re.M))
    body = json.dumps(icons, indent=0, sort_keys=True).replace('",\n"', '",\n  "')
    kinds_src = (ROOT / "src/lib/fileKinds.ts").read_text(encoding="utf-8")
    kinds = {k: {"label": label, "color": color, "icon": ic} for k, label, color, ic in re.findall(
        r'(\w+): \{ label: "([^"]+)", color: "([^"]+)", icon: "(\w+)" \}', kinds_src)}
    (HERE / "kit/icons.js").write_text(
        "// Generated by docs/brand/render.py from src/figma/icons.tsx and src/lib/fileKinds.ts. Do not edit.\n"
        f"window.KINDS = {json.dumps(kinds)};\n"
        f"window.IC = {body};\n"
        "window.icon = (name, size = 16, cls = '') =>\n"
        "  `<svg class=\"${cls}\" width=\"${size}\" height=\"${size}\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" "
        "stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"${window.IC[name] || ''}\"/></svg>`;\n",
        encoding="utf-8",
    )
    print(f"kit/icons.js: {len(icons)} icons")


def browser_path() -> str | None:
    sys.path.insert(0, str(ROOT))
    try:
        from engine.clearcote_manager import get_clearcote_executable
        exe = get_clearcote_executable()
        return str(exe) if exe else None
    except Exception as exc:  # the kit still renders with patchright's Chromium
        print(f"Clearcote not available ({exc}); using patchright's Chromium")
        return None


def url_of(page: str) -> str:
    path, _, query = page.partition("?")
    return (HERE / path).as_uri() + (f"?{query}" if query else "")


def launch(p):
    return p.chromium.launch(executable_path=browser_path(), headless=True,
                             args=["--force-color-profile=srgb", "--font-render-hinting=none"])


def main_world(tab):
    """patchright evaluates in an isolated world by default; page globals live in the main one."""
    class Main:
        def evaluate(self, expr):
            return tab.evaluate(expr, isolated_context=False)
        def wait_for_function(self, expr, timeout):
            deadline = time.time() + timeout / 1000
            while not tab.evaluate(expr, isolated_context=False):
                if time.time() > deadline:
                    raise TimeoutError(expr)
                tab.wait_for_timeout(50)
    return Main()


def open_page(browser, page: str, w: int, h: int, scale: float):
    ctx = browser.new_context(viewport={"width": w, "height": h}, device_scale_factor=scale)
    tab = ctx.new_page()
    errors: list[str] = []
    tab.on("pageerror", lambda e: errors.append(str(e)))
    tab.on("console", lambda m: errors.append(m.text) if m.type == "error" else None)
    tab.goto(url_of(page), wait_until="load")
    tab.evaluate("document.fonts.ready")
    main_world(tab).wait_for_function("window.__ready === true", timeout=15000)
    return ctx, tab, errors


def render_stills(only: list[str]) -> None:
    from PIL import Image
    from patchright.sync_api import sync_playwright

    with sync_playwright() as p:
        browser = launch(p)
        for name, page, w, h in STILLS:
            if only and name not in only:
                continue
            ctx, tab, errors = open_page(browser, page, w, h, 2)
            big = HERE / f".{name}@2x.png"
            tab.screenshot(path=str(big))
            Image.open(big).convert("RGB").resize((w, h), Image.LANCZOS).save(HERE / f"{name}.png", optimize=True)
            big.unlink()
            ctx.close()
            print(f"{name}.png {w}x{h}" + (f"  page errors: {errors}" if errors else ""))
        browser.close()


def capture_demo(theme: str, frames: Path) -> None:
    """Seek the demo frame by frame and screenshot each one into `frames`."""
    from patchright.sync_api import sync_playwright

    with sync_playwright() as p:
        browser = launch(p)
        ctx, tab, errors = open_page(browser, f"{DEMO['page']}&theme={theme}", DEMO["w"], DEMO["h"], DEMO["scale"])
        page = main_world(tab)
        count = int(page.evaluate("window.__duration") * DEMO["fps"])
        for i in range(count):
            page.evaluate(f"window.__seek({i / DEMO['fps']})")
            tab.screenshot(path=str(frames / f"f{i:05d}.png"))
            if i % 150 == 0:
                print(f"{theme}: frame {i}/{count}")
        if errors:
            print("page errors:", errors)
        browser.close()


def ffmpeg(*args: str) -> None:
    subprocess.run([FFMPEG, "-y", "-loglevel", "error", *args], check=True)


def render_demo(themes: list[str]) -> None:
    for theme in themes or ["dark", "light"]:
        frames = Path(tempfile.mkdtemp(prefix=f"mossdl-demo-{theme}-"))
        capture_demo(theme, frames)
        mp4 = HERE / ("demo.mp4" if theme == "dark" else f"demo-{theme}.mp4")
        ffmpeg("-framerate", str(DEMO["fps"]), "-i", str(frames / "f%05d.png"), "-c:v", "libx264", "-preset", "slow",
               "-crf", "24", "-pix_fmt", "yuv420p", "-tune", "animation", "-movflags", "+faststart", str(mp4))
        if theme == "dark":
            shutil.copy(frames / f"f{int(POSTER_AT * DEMO['fps']):05d}.png", HERE / "demo-poster.png")
        # The GIF starts on the finished title card, so its first frame reads on its own
        # (GitHub shows only that frame to people who prefer reduced motion).
        gif = HERE / f"demo-{theme}.gif"
        ffmpeg("-ss", str(GIF["start"]), "-i", str(mp4), "-vf",
               f"fps={GIF['fps']},scale={GIF['width']}:-1:flags=lanczos,split[a][b];"
               f"[a]palettegen=max_colors={GIF['colors']}:stats_mode=diff[p];[b][p]paletteuse=dither=none:diff_mode=rectangle",
               str(gif))
        if theme == "dark":
            shutil.copy(gif, HERE / "demo.gif")
        shutil.rmtree(frames, ignore_errors=True)
        for f in (mp4, gif):
            print(f"{f.name}: {f.stat().st_size / 1e6:.2f} MB")


def main(argv: list[str]) -> None:
    what, rest = (argv[0], argv[1:]) if argv else ("all", [])
    if what in ("icons", "all"):
        gen_icons()
    if what in ("stills", "all"):
        render_stills(rest)
    if what in ("demo", "all"):
        render_demo(rest if what == "demo" else [])


if __name__ == "__main__":
    main(sys.argv[1:])
