// VPN provider presets: the written setup guides shown in Connections.

export interface VpnPreset {
  id: string;
  name: string;
  badge: string;
  color: string;
  guideUrl: string;
  openSourceGuideUrl?: string;
  githubToolUrl?: string;
  githubToolLabel?: string;
  setupSteps?: string[];
  configNotes?: string;
  defaultEndpoint: string;
  templateConf: string;
}

export const TOP_VPN_PRESETS: VpnPreset[] = [
  {
    id: "mullvad",
    name: "Mullvad VPN",
    badge: "WireGuard",
    color: "#eab308",
    guideUrl: "https://mullvad.net/account/#/wireguard-config",
    openSourceGuideUrl: "https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/mullvad.md",
    setupSteps: [
      "Log into your account at mullvad.net",
      "Navigate to 'WireGuard configuration'",
      "Select your target country/city and click 'Generate key'",
      "Download the .conf file and drop or paste it below",
    ],
    configNotes: "Zero personal data. Direct 1-click .conf download with 10.64.0.1/32 address space.",
    defaultEndpoint: "193.138.218.71:51820",
    templateConf: `[Interface]\nPrivateKey = <Your-Mullvad-PrivateKey>\nAddress = 10.64.0.1/32\nDNS = 100.64.0.7\n\n[Peer]\nPublicKey = <Server-PublicKey>\nEndpoint = 193.138.218.71:51820\nAllowedIPs = 0.0.0.0/0`,
  },
  {
    id: "proton",
    name: "Proton VPN",
    badge: "WireGuard",
    color: "#8b5cf6",
    guideUrl: "https://account.protonvpn.com/downloads#wireguard-configuration",
    openSourceGuideUrl: "https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/protonvpn.md",
    githubToolUrl: "https://github.com/hatemosphere/protonvpn-wg-confgen",
    githubToolLabel: "Proton ConfGen (Go CLI)",
    setupSteps: [
      "Log into account.protonvpn.com",
      "Navigate to Downloads → 'WireGuard configuration'",
      "Select your platform, country, server, and NetShield settings",
      "Download the .conf file and import it below",
    ],
    configNotes: "Native manual config generator with NetShield ad/malware blocking. Uses 10.2.0.2/32.",
    defaultEndpoint: "185.159.157.1:51820",
    templateConf: `[Interface]\nPrivateKey = <Your-Proton-PrivateKey>\nAddress = 10.2.0.2/32\nDNS = 10.2.0.1\n\n[Peer]\nPublicKey = <Server-PublicKey>\nEndpoint = 185.159.157.1:51820\nAllowedIPs = 0.0.0.0/0`,
  },
  {
    id: "ivpn",
    name: "IVPN",
    badge: "WireGuard",
    color: "#3b82f6",
    guideUrl: "https://www.ivpn.net/account/wireguard",
    openSourceGuideUrl: "https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/ivpn.md",
    setupSteps: [
      "Log into your IVPN Client Area",
      "Open the WireGuard tab and click 'Manage Keys'",
      "Click 'Generate WireGuard Key' and select server location",
      "Download the .conf file and drop it below",
    ],
    configNotes: "Supports alternate listening ports (2049, 53, 1194, 51820) to bypass restrictive firewalls.",
    defaultEndpoint: "198.51.100.1:2049",
    templateConf: `[Interface]\nPrivateKey = <Your-IVPN-PrivateKey>\nAddress = 172.16.0.2/32\nDNS = 10.0.254.1\n\n[Peer]\nPublicKey = <Server-PublicKey>\nEndpoint = 198.51.100.1:2049\nAllowedIPs = 0.0.0.0/0`,
  },
  {
    id: "nordvpn",
    name: "NordVPN (NordLynx)",
    badge: "WireGuard",
    color: "#06b6d4",
    guideUrl: "https://my.nordaccount.com/dashboard/nordvpn/manual-configuration/",
    openSourceGuideUrl: "https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/nordvpn.md",
    githubToolUrl: "https://github.com/FinleyJDev/NordLynx-WireGuard-Config-Generator",
    githubToolLabel: "NordLynx Generator (PowerShell)",
    setupSteps: [
      "Log into my.nordaccount.com and generate a 'Manual connection access token'",
      "Run the open-source NordLynx Config Generator script with your token",
      "The tool calls Nord's API and exports standard .conf files for any country",
      "Import the exported .conf file below",
    ],
    configNotes: "NordVPN uses proprietary NordLynx. Community scripts export standard WireGuard .conf files via token.",
    defaultEndpoint: "us9999.nordvpn.com:51820",
    templateConf: `[Interface]\nPrivateKey = <Your-NordLynx-PrivateKey>\nAddress = 10.5.0.2/32\nDNS = 103.86.96.100\n\n[Peer]\nPublicKey = <Server-PublicKey>\nEndpoint = us9999.nordvpn.com:51820\nAllowedIPs = 0.0.0.0/0`,
  },
  {
    id: "surfshark",
    name: "Surfshark",
    badge: "WireGuard",
    color: "#10b981",
    guideUrl: "https://my.surfshark.com/vpn/manual-setup/main/wireguard",
    openSourceGuideUrl: "https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/surfshark.md",
    setupSteps: [
      "Log into your account at my.surfshark.com",
      "Navigate to VPN → Manual setup → WireGuard",
      "Click 'I don't have a key pair' to generate one, then pick a server location",
      "Download the configuration file and drop it below",
    ],
    configNotes: "Standard WireGuard configuration with 10.14.0.2/16 address space and multi-location endpoints.",
    defaultEndpoint: "us-nyc.prod.surfshark.com:51820",
    templateConf: `[Interface]\nPrivateKey = <Your-Surfshark-PrivateKey>\nAddress = 10.14.0.2/16\nDNS = 162.252.172.57\n\n[Peer]\nPublicKey = <Server-PublicKey>\nEndpoint = us-nyc.prod.surfshark.com:51820\nAllowedIPs = 0.0.0.0/0`,
  },
  {
    id: "windscribe",
    name: "Windscribe",
    badge: "WireGuard",
    color: "#ec4899",
    guideUrl: "https://windscribe.com/getconfig/wireguard",
    openSourceGuideUrl: "https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/windscribe.md",
    setupSteps: [
      "Log into your account at windscribe.com",
      "Navigate to Account → WireGuard Configs",
      "Select your preferred server location and listening port (port 443 recommended)",
      "Download the .conf file and drop it below",
    ],
    configNotes: "Port 443 support allows WireGuard traffic to masquerade as standard HTTPS through firewalls.",
    defaultEndpoint: "us-east-wg.windscribe.com:443",
    templateConf: `[Interface]\nPrivateKey = <Your-Windscribe-PrivateKey>\nAddress = 10.124.0.2/32\nDNS = 10.255.255.1\n\n[Peer]\nPublicKey = <Server-PublicKey>\nEndpoint = us-east-wg.windscribe.com:443\nAllowedIPs = 0.0.0.0/0`,
  },
  {
    id: "airvpn",
    name: "AirVPN",
    badge: "WireGuard",
    color: "#f97316",
    guideUrl: "https://airvpn.org/generator/",
    openSourceGuideUrl: "https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/airvpn.md",
    setupSteps: [
      "Log into your AirVPN Client Area",
      "Go to Config Generator → select Protocol: WireGuard",
      "Choose your desired server location, port, and key",
      "Click Generate and drop the downloaded .conf file below",
    ],
    configNotes: "Full port forwarding and custom MTU/port selection supported natively.",
    defaultEndpoint: "198.51.100.5:1637",
    templateConf: `[Interface]\nPrivateKey = <Your-AirVPN-PrivateKey>\nAddress = 10.128.0.2/16\nDNS = 10.128.0.1\n\n[Peer]\nPublicKey = <Server-PublicKey>\nEndpoint = 198.51.100.5:1637\nAllowedIPs = 0.0.0.0/0`,
  },
  {
    id: "pia",
    name: "Private Internet Access",
    badge: "WireGuard",
    color: "#22c55e",
    guideUrl: "https://www.privateinternetaccess.com/helpdesk/guides/",
    openSourceGuideUrl: "https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/private-internet-access.md",
    githubToolUrl: "https://github.com/pia-foss/manual-connections",
    githubToolLabel: "PIA Official Manual Setup (FOSS)",
    setupSteps: [
      "PIA uses dynamic REST API token generation for WireGuard",
      "Run the official pia-foss/manual-connections script or pia-wg tool",
      "Authenticate with your PIA account credentials to generate your local config",
      "Drop the generated pia.conf file below",
    ],
    configNotes: "Official open-source scripts handle dynamic key rotation and token generation.",
    defaultEndpoint: "us-newyorkcity.privacy.network:1337",
    templateConf: `[Interface]\nPrivateKey = <Your-PIA-PrivateKey>\nAddress = 10.0.0.2/32\nDNS = 10.0.0.242\n\n[Peer]\nPublicKey = <Server-PublicKey>\nEndpoint = us-newyorkcity.privacy.network:1337\nAllowedIPs = 0.0.0.0/0`,
  },
  {
    id: "ovpn",
    name: "OVPN",
    badge: "WireGuard",
    color: "#6366f1",
    guideUrl: "https://www.ovpn.com/en/wireguard",
    openSourceGuideUrl: "https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/custom.md",
    setupSteps: [
      "Log into your dashboard at ovpn.com",
      "Navigate to Profile → WireGuard",
      "Click 'Generate key', choose your server, and click download",
      "Drop the downloaded .conf file below",
    ],
    configNotes: "High-security Swedish VPN operating RAM-only servers with dedicated 9929 WireGuard port.",
    defaultEndpoint: "vpn01.ovpn.com:9929",
    templateConf: `[Interface]\nPrivateKey = <Your-OVPN-PrivateKey>\nAddress = 10.84.0.2/32\nDNS = 46.227.67.134\n\n[Peer]\nPublicKey = <Server-PublicKey>\nEndpoint = vpn01.ovpn.com:9929\nAllowedIPs = 0.0.0.0/0`,
  },
  {
    id: "warp",
    name: "Cloudflare WARP",
    badge: "WireGuard",
    color: "#f59e0b",
    guideUrl: "https://developers.cloudflare.com/warp-client/",
    githubToolUrl: "https://github.com/ViRb3/wgcf",
    githubToolLabel: "wgcf CLI Generator (1-Click Free)",
    setupSteps: [
      "Download the open-source 'wgcf' binary from GitHub",
      "Run 'wgcf register' in your terminal (no account or payment needed)",
      "Run 'wgcf generate' to produce 'wgcf-profile.conf'",
      "Drop the generated wgcf-profile.conf file below",
    ],
    configNotes: "100% free high-speed WireGuard tunnel routed through Cloudflare's Anycast edge network.",
    defaultEndpoint: "engage.cloudflareclient.com:2408",
    templateConf: `[Interface]\nPrivateKey = <Your-WARP-PrivateKey>\nAddress = 172.16.0.2/32\nDNS = 1.1.1.1\n\n[Peer]\nPublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=\nEndpoint = engage.cloudflareclient.com:2408\nAllowedIPs = 0.0.0.0/0`,
  },
  {
    id: "expressvpn",
    name: "ExpressVPN",
    badge: "WireGuard / Lightway",
    color: "#da291c",
    guideUrl: "https://www.expressvpn.com/setup#manual",
    openSourceGuideUrl: "https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/expressvpn.md",
    setupSteps: [
      "ExpressVPN uses proprietary Lightway instead of standard WireGuard",
      "Connect through ExpressVPN's desktop application or export an OpenVPN config",
      "In MossDL, select 'System VPN' adapter mode to route through ExpressVPN",
    ],
    configNotes: "Does not provide raw WireGuard keys; use the System VPN adapter option in MossDL.",
    defaultEndpoint: "usa-newyork.expressnet.com:51820",
    templateConf: `[Interface]\nPrivateKey = <Your-ExpressVPN-PrivateKey>\nAddress = 10.10.0.2/32\nDNS = 10.10.0.1\n\n[Peer]\nPublicKey = <Server-PublicKey>\nEndpoint = usa-newyork.expressnet.com:51820\nAllowedIPs = 0.0.0.0/0`,
  },
  {
    id: "cyberghost",
    name: "CyberGhost",
    badge: "WireGuard",
    color: "#ffc107",
    guideUrl: "https://my.cyberghostvpn.com/",
    openSourceGuideUrl: "https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/cyberghost.md",
    setupSteps: [
      "Log into your CyberGhost account dashboard",
      "Navigate to VPN → WireGuard → 'Add Device'",
      "Select your target country and city, then download the configuration",
      "Drop the configuration file below",
    ],
    configNotes: "Dedicated fast streaming and download servers on standard 51820 WireGuard port.",
    defaultEndpoint: "us-nyc-wg.cyberghostvpn.com:51820",
    templateConf: `[Interface]\nPrivateKey = <Your-CyberGhost-PrivateKey>\nAddress = 10.10.0.2/32\nDNS = 10.10.0.1\n\n[Peer]\nPublicKey = <Server-PublicKey>\nEndpoint = us-nyc-wg.cyberghostvpn.com:51820\nAllowedIPs = 0.0.0.0/0`,
  },
  {
    id: "ipvanish",
    name: "IPVanish",
    badge: "WireGuard",
    color: "#4caf50",
    guideUrl: "https://account.ipvanish.com/",
    openSourceGuideUrl: "https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/ipvanish.md",
    setupSteps: [
      "Log into account.ipvanish.com",
      "Navigate to Server List or Manual Configurations",
      "Select WireGuard, generate your keypair for the chosen region, and download",
      "Drop the .conf file below",
    ],
    configNotes: "Uses 172.24.0.2/32 subnet with standard 51820 port.",
    defaultEndpoint: "nyc-a01.ipvanish.com:51820",
    templateConf: `[Interface]\nPrivateKey = <Your-IPVanish-PrivateKey>\nAddress = 172.24.0.2/32\nDNS = 172.24.0.1\n\n[Peer]\nPublicKey = <Server-PublicKey>\nEndpoint = nyc-a01.ipvanish.com:51820\nAllowedIPs = 0.0.0.0/0`,
  },
  {
    id: "tailscale",
    name: "Tailscale",
    badge: "Mesh Network",
    color: "#2563eb",
    guideUrl: "https://tailscale.com/kb/1017/install",
    setupSteps: [
      "Install Tailscale from tailscale.com",
      "Log into your tailnet to connect your devices",
      "Export node keys or select the Tailscale adapter under System VPN in MossDL",
    ],
    configNotes: "Peer-to-peer WireGuard mesh networking over 100.64.0.0/10 CGNAT address space.",
    defaultEndpoint: "100.100.100.100:41641",
    templateConf: `[Interface]\nPrivateKey = <Your-Tailscale-PrivateKey>\nAddress = 100.64.0.2/32\nDNS = 100.100.100.100\n\n[Peer]\nPublicKey = <Node-PublicKey>\nEndpoint = 100.100.100.100:41641\nAllowedIPs = 100.64.0.0/10`,
  },
  {
    id: "tor",
    name: "Tor Onion Proxy",
    badge: "SOCKS5 Proxy",
    color: "#7e22ce",
    guideUrl: "https://www.torproject.org/",
    setupSteps: [
      "Install and start Tor Browser or the Tor background daemon",
      "Verify Tor is listening on local SOCKS5 port 9050 or 9150",
      "Use the SOCKS5 proxy configuration in MossDL to route traffic anonymously",
    ],
    configNotes: "Onion-routed multi-hop anonymity proxy listening on 127.0.0.1:9050.",
    defaultEndpoint: "127.0.0.1:9050",
    templateConf: `[Proxy]\nKind = socks5\nEndpoint = 127.0.0.1:9050\nDNS = remote`,
  },
];
